### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by vinceferro** [surgeforward/sb-admin-2-ember-cli#1]
Hi, could you please post how to use this package?
Thank you

**Comment by edsadr** [comment]
+1 looks really interesting but no idea how to use this

**Comment by vinceferro** [comment]
I've tried including it in package.json but there were some errors on glob instructions.
I got it working using bower, broccoli-static-compiler, broccoli-merge-trees and a few lines of code in Brocfile.js to import all the dependencies.

**Comment by eibrahim** [comment]
I will put some docs together soon. Can you share the errors and fix?

On Mon, Mar 9, 2015 at 3:32 AM -0700, "Vincenzo Ferrara" notifications@github.com wrote:

I've tried including it in package.json but there were some errors on glob instructions.

I got it working using bower, broccoli-static-compiler, broccoli-merge-trees and a few lines of code in Brocfile.js to import all the dependencies.

**Comment by vinceferro** [comment]
This is the error building the ember project.

![schermata 2015-03-09 alle 12 47 05](https://cloud.githubusercontent.com/assets/1297351/6554309/78f5be4e-c65a-11e4-80fb-3c09d849c322.png)

I ended up installing startbootstrap-sb-admin-2 via bower and then import the dependencies in Brocfile.js

``` javascript

/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp();

// Use `app.import` to add additional libraries to the generated
// output files.
//
// If you need to use different assets in different
// environments, specify an object as the first parameter. That
// object's keys should be the environment name and the values
// should be the asset to use in that environment.
//
// If the library that you are including contains AMD or ES6
// modules that you would like to import into your application
// please specify an object with the list of modules as keys
// along with the exports of each module as its value.

var pickFiles = require('broccoli-static-compiler');
var mergeTrees = require('broccoli-merge-trees');

var bootstrap = pickFiles('bower_components/bootstrap/dist', {
  srcDir: '/css',
  files: ['bootstrap.min.css'],
  destDir: '/assets/css'
});

var bootstrapFont = pickFiles('bower_components/bootstrap/dist', {
  srcDir: '/fonts',
  destDir: '/assets/fonts'
});

var metisMenu = pickFiles('bower_components/metisMenu/dist', {
  srcDir: '.',
  files: ['*.min.css'],
  destDir: '/assets/css'
});

var sbAdmin = pickFiles('bower_components/startbootstrap-sb-admin-2/dist', {
  srcDir: '/css',
  destDir: '/assets/css'
});

var fontAwesome = pickFiles('bower_components/font-awesome', {
  srcDir: '/css',
  files: ['*.min.css'],
  destDir: '/assets/css'
});

var fontAwesomeFonts = pickFiles('bower_components/font-awesome', {
  srcDir: '/fonts',
  destDir: '/assets/fonts'
});

var bootstrapjs = pickFiles('bower_components/bootstrap/dist', {
  srcDir: '/js',
  files: ['bootstrap.min.js'],
  destDir: '/assets/js'
});

var sbAdminJS = pickFiles('bower_components/startbootstrap-sb-admin-2/dist', {
  srcDir: '/js',
  destDir: '/assets/js'
});

app.import('bower_components/metisMenu/dist/metisMenu.min.js');

var outputTree = mergeTrees([
  bootstrap,
  bootstrapFont,
  metisMenu,
  sbAdmin,
  fontAwesome,
  fontAwesomeFonts,
  bootstrapjs,
  sbAdminJS,
  app.toTree()]);

module.exports = outputTree;

```

**Comment by eibrahim** [comment]
Thanks for the detailed response.   I will look into it and update the docs as well as upgrade to latest version soon - stay tuned.

**Comment by edsadr** [comment]
much appreciated, I had to include all things manually.... but I am willing to test and later maybe to contribute

**Comment by eibrahim** [comment]
I updated the readme and fixed the issues.  Take a look and let me know.

**Comment by vinceferro** [comment]
Hi, still getting errors on `ember build` and `ember serve`

**Comment by eibrahim** [comment]
Can you post the error and more details about your ember and cli versions?  Have you tried adding it to a new project and see if it works?
